Repository nimblehq/JSONMapper, pull requests merged in 2022-05, with the labels that each got.

#7 [#6] Add cocoapods support
  .swiftpm/xcode/package.xcworkspace/contents.xcworkspacedata
  JSONAPIMapper.podspec
  Package.swift
  README.md
  Sources/JSONAPIMapper/Extensions/Optional+Extras.swift
  Sources/JSONAPIMapper/JSONAPIDecoder.swift
  Sources/JSONAPIMapper/Models/DataType.swift
  Sources/JSONAPIMapper/Models/JSON.swift
  Sources/JSONAPIMapper/Models/JSONAPIDecodingError.swift
  Sources/JSONAPIMapper/Models/JSONAPIError.swift
  Sources/JSONAPIMapper/Models/JSONAPIObject.swift
  Sources/JSONAPIMapper/Models/JSONAPIType.swift
  Sources/JSONAPIMapper/Models/Link.swift
  Sources/JSONAPIMapper/Models/Links.swift
  Sources/JSONAPIMapper/Models/Relationship.swift
  Sources/JSONAPIMapper/Models/Resource.swift
  Sources/JSONAPIMapper/Models/ResourceIdentifier.swift
  Tests/JSONAPIMapperTests/JSONMapperTests.swift
  Tests/JSONMapperTests/JSONMapperTests.swift
Labels: type : feature

#9 [#8] Fix: Unable to access JSONAPIError.source.paramater
  Sources/JSONAPIMapper/Models/JSONAPIError.swift
Labels: type : bug

#11 [#10] Bump version to 1.1.1
  JSONAPIMapper.podspec
  README.md
Labels: type : chore

#12 Release - 1.1.1
  JSONAPIMapper.podspec
  README.md
  Sources/JSONAPIMapper/Models/JSONAPIError.swift
Labels: type : release
